# Generated by Django 2.0.4 on 2018-04-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_auto_20180418_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
