# Generated by Django 2.0.4 on 2018-04-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_auto_20180420_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stopword',
            name='stop_word',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
