# Generated by Django 2.0.4 on 2018-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_auto_20180423_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word2Vec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.BinaryField()),
                ('syn0', models.BinaryField()),
                ('syn1neg', models.BinaryField()),
            ],
        ),
    ]
