# Generated by Django 2.0.4 on 2018-04-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_auto_20180419_0212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
