# Generated by Django 2.0.4 on 2018-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_auto_20180419_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
