# Generated by Django 2.0.4 on 2018-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0005_auto_20180419_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=30),
        ),
    ]
