# Generated by Django 2.0.4 on 2018-04-27 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0005_auto_20180426_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word2VecModel',
        ),
    ]
