# Generated by Django 2.0.4 on 2018-04-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0006_auto_20180419_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_word', models.CharField(max_length=30)),
            ],
        ),
    ]
